language: cpp
git:
  depth: 100
notifications:
  email: false
env:
  global:
    - RT_URL=github.com/bigladder/kiva-test-results.git
    - RT_DIR=build/test/results
    - secure: "m6BS+3JWbJHJOXPGmF3hS4vng7kEUErkjcHDeIgbctMEZvHFbctniWJJ70V1rM6bLalA2PLCBNygWbXHuBIaFcHto06QcmR4q7EHcTJHpN5nYJqce5yI8UPAaPqC3tScVfrJoDdoqQitfq60iYr2gDdHlviOiNw1GOZeR5z+gINNtFq91qcsB5rQoEUPOTM7fJZ59WvrjZAkwcls0lI3yCg750Ep7GFiILhkiqBBiGLMxLtyJaNNgch2RIyZayZS+f2VGsF8UcFY7aQpYgKyJ0CfqwLPN4aL9q7wZ99wT0QvqRe+a9l/rTOg1h3pEb4f5+63etZNZkaqBB+aZY9gGVRhLlc99FMAYD0oNg6TGCSx5RnV1k3PkC6dvuXkLOJKTTgnXOkmCUHuyhgNZgTYasNZXhij9Bso8CBRKkEQe9afvRuM6+FymkZIKsJ2YjN6C7Cf5HRjPkOYOkhYxecIo7lzn6dInhata7FsnfQfFz+GPVN9/3k0mrhWu3kUKIncyrnttYIzxEOpiE5PUFdkOt1fQ1sAvAKFMCa6v/go0jt2LuJplA1nwFBX+WjbcXnq7wKqE9bPbeB/hwwMrrGJr8YmDnykdiLZOZa05h583f6NRdzJhBDEfL8Gd4f+dc22sib8kEPBm4eKMBdFWCmyUondl6ZgVH1GYIhRa7mpzZE="
    - secure: "oJ4MlIOUnHTKP4nfED5Hr1SWjQHCtZzP2ME/yCM3hEZtWE018UeV80sK6QDQtw2+iyNLiPf1NF95PySUvwsdmwo4mKd8fjo1ANc9+nJEI0MTiy0kDdsMSvpEkfZghpTdWlP38YToYiKW5F8ocOC9hAiV0CV5OfSTICAvBxuddjRbsJDFloSxOv2gjMV+iMjw8Hc36u/uOA7DzRIHe2PK9sRKWRFCPVGj8D0i35MnV56O+va86fPH3iAREGkAO8OF6olovjzWyArjgOwtx2vl+eYt634lcA7Kcq5vIsB58fQB4Y0zwzu+2QnRWbjYNblFwg8k1FC6+kNNridnWt1Hydspij+gbkTMWhB/DJpH1d/6Ahncb0ZgpDNXiMiTqa091AwXnmaWdxWI3Y948tKq6jl1fPsQnarqo6EjMc7oXvAhUW4kxzcgOZmgRhoZHvHi1d0uEWaR9G6WQ6UQUZfGZbITt5oGRge7GhBdFcQg3zKIXPbHakMtnVPYfrOYJdiDAcgpkk7EdukONhL40sPkQOenXui98dsnNixFX2x2aLlPKY/ctL9XX6f3GBJt/JHDtgsTksPqfNV2WiMOVoz7ya9F3hD0kQGKSmjKalkHCZ87lLxxSxmx4WyO+azMRKueJc8UnTi2NtQCGRGOUqBOHrhpMtUUuiNbRejvWuv2FPA="
    - secure: "CYPZZkDZftNiYSathjGcwnUGQcgF7xYHWTrkp17BdtncwufjXcoNTYlG5tjLt2FHWjZe8YPemTDqFb6MSfKBHh16JGdocaxsaUvv1HkLYmSpg/aYi8Jor71PQHYedjUEkLRFfmPSvolMT/czoB9IhRfO14udbYqQO+jcg/P3iITfWEnihU98wgHEg6XGNrXOT5LMJn8cQBOFbvBCQQhK0S8eMs2d5LEaS/HpmsLld1hFA3RyO+3Gp4oXVeaMCwD86Mp3coomDpTneSk/RlPNsIPaz37NUXCN29Atq2XIT1Oi4Etmp/f0TizDGdOMRJDsvV3VftRCCUf+zuAL9TUUjdGxtYZWwZf/I4mDUCYidP8mV+MRUAuGKUdJSv9l1P0FUIWEcr/vxIKSxbNdsApzQOTj3OcL1UAflV/czfnIL4YOvPizvxPk7zIR9hV89JLr1+9gD4nWrbrk29mnJk6a2Ke/NSO2Ju3XnCLohyVMFk8EDL8x1kAnT8axSVy0RD4zs8aPbwejSBrUnbxaEoArEO2RGsqk1uoz/PmC9PR8UuJ7a+DgomY4YQOjASdAVysABBVOMJmZrPvMb4zQ1qmGcztvoPG0xXdMMyWeVFqqxom3YzOixjOXfymlBy6ab1oZMV9gK6wZdARBNusP1wZ1KWekbBx7jkVlTYBictMqHAI="
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: COMPILER=clang COVERAGE=false
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: COMPILER=gcc COVERAGE=false
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: COMPILER=gcc COVERAGE=true
before_install:
  - if [[ "$COVERAGE" == false ]]; then
      rvm install 2.0.0;
      gem install git;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm use 2.3;
      brew install gcc;
      rvm use 2.0;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -y -qq update;
      sudo apt-get -y install cmake;
      sudo apt-get -y install gfortran;
    fi
  - cmake --version

script:
  - mkdir build
  - cd build
  - if [[ "$COVERAGE" == false ]]; then
      ruby -e "puts(RUBY_PLATFORM)";
      export SRC_BRANCH=$TRAVIS_BRANCH;
      cmake -DKIVA_STATIC_LIB=OFF ..;
      ruby ../scripts/clone-and-mimic.rb;
    else
      cmake -DKIVA_COVERAGE=ON -DKIVA_STATIC_LIB=OFF -DCMAKE_BUILD_TYPE=Debug ..;
    fi
  - make -j
  - >
    if [[ "$COVERAGE" == true ]]; then
      ctest -R integration\.
      make gcov;
      bash <(curl -s https://codecov.io/bash) -X gcov -cF integration;
      ctest -R unit\.
      make gcov;
      bash <(curl -s https://codecov.io/bash) -X gcov -cF unit;
    else
      ctest --output-on-failure
    fi

after_success:
  - if [[ "$COVERAGE" == false ]]; then
      ruby ../scripts/log-results.rb;
      cpack -B "$TRAVIS_BUILD_DIR";
      cd "$TRAVIS_BUILD_DIR";
    fi

deploy:
  provider: script
  skip_cleanup: true
  script: "curl --ftp-create-dirs -T kiva*.zip -u $FTP_USER:$FTP_PASSWORD ftp://downloads.bigladdersoftware.com/downloads.bigladdersoftware.com/files/"
  on:
    all_branches: true
    condition: "\"$COVERAGE\" == false"
    tags: true
